pretrained_weights: False
num_workers: 8
fix_seed: False
result_path: ./results

train_settings:
  train_path: ../curl_custom_dataset_V10
  train_batch_size: 1
  num_epochs: 80
  shuffle: True
  h_input: null
  w_input: null
  random_resize: False
  random_crop: False
  mixed_precision: True

valid_settings:
  valid_path: ../curl_custom_dataset_V10
  valid_batch_size: 1
  do_every: 5
  device: cuda
  plot: False
  log: True

test_settings:
  test_path: ../curl_custom_dataset_V10
  test_batch_size: 1
  do_every: 5
  device: cuda
  plot: True
  log: True

optimizer:
  name: AdamW
  lr: 6e-5
  weight_decouple: True
  weight_decay: 0.005
  eps: 1e-8
  grad_clip_norm: 1.0
  decay:
    warmup: 3
    min_lr: 5e-6
    gamma: 1.0